spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: productshop
  datasource:
    url: jdbc:mysql://localhost:3306/productshop
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  jpa.properties:
    hibernate:
      show_sql: true
      format_sql: true
      use_sql_comments: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
    protocol: smtp
  data:
    redis:
      host: redis
      port: 6379
