name: CI/CD Pipeline

on:
  push:
    branches:
      - ci2

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle (without tests)
        run: ./gradlew build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image with tests
        run: |
          docker build -t my-spring-boot-app:test .
          
          # Run tests within the Docker container
          docker run --rm \
            -e SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
            -e SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
            -e AES_ALG=${{ secrets.AES_ALG }} \
            -e AES_KEY=${{ secrets.AES_KEY }} \
            -e MAIL_HOST=${{ secrets.MAIL_HOST }} \
            -e MAIL_PORT=${{ secrets.MAIL_PORT }} \
            -e MAIL_USERNAME=${{ secrets.MAIL_USERNAME }} \
            -e MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} \
            -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
            -e AUTHORIZATION_HEADER=${{ secrets.AUTHORIZATION_HEADER }} \
            -e REFRESHTOKEN_HEADER=${{ secrets.REFRESHTOKEN_HEADER }} \
            -e TOKEN_KEY=${{ secrets.TOKEN_KEY }} \
            -e ACCESS_TOKEN_TIME=${{ secrets.ACCESS_TOKEN_TIME }} \
            -e REFRESH_TOKEN_TIME=${{ secrets.REFRESH_TOKEN_TIME }} \
            -e ACCESS_TOKEN_NAME=${{ secrets.ACCESS_TOKEN_NAME }} \
            -e REFRESH_TOKEN_NAME=${{ secrets.REFRESH_TOKEN_NAME }} \
            -e MYSQL_SERVER=${{ secrets.MYSQL_SERVER }} \
            my-spring-boot-app:test ./gradlew test

      - name: Push Docker image if tests pass
        run: |
          docker tag my-spring-boot-app:test ${{ secrets.DOCKER_USERNAME }}/my-spring-boot-app:test
          docker push ${{ secrets.DOCKER_USERNAME }}/my-spring-boot-app:test

      - name: Logout from Docker Hub
        run: docker logout
